import type { WorkflowId } from "./workflows";

export const SAMPLE_WORKFLOWS: Record<WorkflowId, string> = {
  "customer-success": `We have 340 mid-market SaaS customers. Health scoring is a monthly export from Gainsight into a Google Sheet, blended with support ticket counts and a manual "sentiment" column CSMs fill in. CSMs each own ~50 accounts; no formal segmentation by risk. Renewal work starts 60 days out. In the last 4 quarters GRR dropped from 92% to 87%. Most churn "surprises" us — we knew the customer was there, but the health score didn't shift until the renewal call. Onboarding takes 47 days on average against a 30-day target. Our CS Ops person left 3 months ago and hasn't been backfilled. Exec sponsors change ~40% of the time in year 2 and we don't have a play for it.`,

  revops: `Series C, 180 reps across SMB / MM / ENT. Salesforce is source of truth but 34% of closed-won opps last quarter had incomplete stage histories — reps update the record after the deal closes. Forecast rollups happen in a spreadsheet an analyst rebuilds every Monday. Marketo → Salesforce lead sync has been "flaky" for 6 months and no one has scoped the fix. AE-to-SE ratio is 4:1 but SEs are booked 3 weeks out. Deal desk requests average 6-day turnaround against a 48-hour target. We're missing the quarter by ~$3M and can't tell if it's coverage, conversion, or forecast noise. RevOps team is 3 people including the leader.`,

  recruiting: `We hire ~40 engineers/quarter across two products. Sourcing is 60% inbound via careers page, 40% split across 3 agencies and 1 internal sourcer. Screen → onsite conversion is 22% (industry benchmark ~30%). Onsite → offer is 55%. Offer accept rate dropped from 78% to 61% over two quarters. Interview panels are booked in Greenhouse but interviewer load is uneven — 8 people do 60% of the interviews. Recruiting coordinator is a single person managing 25 open reqs. Time-to-fill has grown from 38 days to 61 days. Hiring managers say candidates are lower quality; recruiters say the hiring bar keeps shifting between panels.`,

  "workforce-planning": `2,400 employees, 6 business units. Headcount plan is set annually in a spreadsheet by Finance, then negotiated with BU leaders. Skills inventory lives in Workday but "current role" is the only reliable field — no reliable data on side projects, certifications, or stated interests. Three declared strategic priorities this year (AI product, EMEA expansion, platform re-architecture) and none has a headcount plan tied to the strategy. Attrition is 14% overall, 22% in engineering. Internal transfer rate is 3% against a 10% target. We laid off 8% last year and are now backfilling ~40% of those roles externally. Talent Acquisition and L&D report to different orgs and have not shared a joint plan in 3 years.`,

  "insurance-ops": `Regional commercial-lines carrier, ~$400M written premium. Quote turnaround is 4.2 days against a 2-day target. Underwriters manually pull 6-8 external data sources per quote. Bind rate on quotes is 31% and we can't tell why the other 69% don't bind — there's no structured "reason not bound" field. Claims: first notice of loss (FNOL) triage is a call-center scripted decision tree; ~18% of claims get re-routed after initial triage, adding 6 days on average. Compliance review is a single team of 4 handling all lines; they're the bottleneck for 3 of our 7 product launches this year. Broker portal has a 2.3/5 satisfaction score and the top complaint is "I can't tell what stage my quote is in."`,

  "healthcare-marketing-ops": `Specialty pharma, 3 launched products plus 2 in-flight launches. HCP campaigns run across email, field-rep triggers, and 3rd-party publishers. MLR review takes 14 days on average against a 7-day target; ~40% of assets go through 2+ revision cycles. Omnichannel orchestration today is "email calendar Tuesdays, rep call plans monthly, publisher buys quarterly" — no unified next-best-action engine. Consent and PHI: separate consent systems for HCP vs patient with no unified view. Measurement is siloed — email opens in Marketo, rep calls in Veeva, digital in Snowflake. Attribution on script lift is done annually by an external agency and takes 8 weeks to deliver. The commercial team wants a real-time next-best-channel recommendation by Q3.`,

  "ai-adoption": `12,000-person financial services firm. Sanctioned AI tools: MS Copilot enterprise (rolled out to 4,000), a sanctioned Claude/OpenAI proxy for engineers. A shadow-AI survey estimates 60% of knowledge workers use unsanctioned LLMs weekly. 14 approved pilots are underway across ops, legal, HR, and customer support — zero in production. Governance sits with a joint IT + Risk + Legal committee that meets biweekly and is the bottleneck for pilot-to-prod graduation. No shared measurement framework — pilots report anecdotal wins in slide decks. The CEO wants a public "AI transformation" story in 6 months. There is no accountable owner for the overall AI portfolio; the CIO, CISO, and Chief Data Officer each think they own a slice.`,
};
